#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later

from os import scandir
from sys import argv

def print_no_lf(*args):
	print(*args, end = '')

def sort_deps(item):
	return not isinstance(item, list)

def child_deps(deps):
	return (item for item in deps[1:] if isinstance(item, list))

def direct_deps(deps):
	return (item for item in deps[1:] if not isinstance(item, list))

def find_deps(dir):
	deps = [ dir ]

	with scandir(dir) as ents:
		ents = sorted(ents, key = lambda ent: ent.name)

		for ent in ents:
			item = ent.path

			if item.endswith('_entry.c'):
				continue

			if ent.is_dir():
				item = find_deps(ent.path)

			deps.append(item)

	deps[1:] = sorted(deps[1:], key = sort_deps)

	return deps

def print_headers(deps, cmdtree):
	for child in child_deps(deps):
		print_headers(child, cmdtree)

	header = deps[0]
	print_no_lf(f"include/{header}/d.h: {cmdtree} |")

	for item in direct_deps(deps):
		print_no_lf(f" {item}")

	print('\n')

def print_object_deps(deps):
	for child in child_deps(deps):
		print_object_deps(child)

	header = deps[0]
	print_no_lf(f"build/{header}.o")

	for item in direct_deps(deps):
		print_no_lf(f" {object_path(item)}")

	print(f": include/{header}/d.h\n")

	print_no_lf(f"build/{header}.d1")

	for item in direct_deps(deps):
		print_no_lf(f" {dependency_path(item)}")

	print(f": include/{header}/d.h\n")

def object_path(item):
	if item.endswith('.c'):
		item = item[0:-2]

	return f"build/{item}.o"

def dependency_path(item):
	return f"{object_path(item)[0:-2]}.d1"

def collect_objects(deps):
	objects = []

	for item in deps:
		if isinstance(item, list):
			objects += collect_objects(item)
			continue

		objects.append(object_path(item))

	return objects

def print_binary_deps(deps):
	seen = set()

	for child in child_deps(deps):
		print_binary_deps(child)

	root = deps[0]
	print_no_lf(f"build/{root}/entry:")
	print_no_lf(f" build/{root}_entry.o")

	for obj in collect_objects(deps):
		if obj in seen:
			continue

		print_no_lf(f" {obj}")
		seen.add(obj)

	print('\n')

def print_command_object_y(deps):
	for child in child_deps(deps):
		print_command_object_y(child)

	root = deps[0]
	print_no_lf('cmd-obj-y +=')
	print_no_lf(f" build/{root}.o")
	print_no_lf(f" build/{root}_entry.o")

	for item in direct_deps(deps):
		print_no_lf(f" {object_path(item)}")

	print('\n')

main = argv[1]
init = main.split('.')[0]
deps = find_deps(init)
cmdtree = f"build/{init.split('/')[0]}/cmdtree"

print(f"# Generated by {argv[0]}\n")

print_headers(deps, cmdtree)

print_object_deps(deps)

print_binary_deps(deps)

print_command_object_y(deps)
