#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

trap 'rm -f .tmp-$$' EXIT

name=$(dirname $1 | cut -d/ -f3- | sed -e 's|main/|/|' -e 's|^/||' -e 's|/|_|g')
class=$(printf '%s' $name | tr '[:lower:]' '[:upper:]')
pretty=$(printf '%s' $name | cut -d_ -f2- | tr _ ' ')

sed_cmd_name='s|.*/\([^/]*\).c|'
opt_cmd_name='\tPA_OPT_CMD("\1", v, cmd_'$name'_\1, cmd_'$name'_\1_help)'

cat >.tmp-$$

cat <<EOF
/* Generated by $0 */

#ifndef CMD_${class}_D_H
#define CMD_${class}_D_H

#include "parse_argv.h"

$(sed $sed_cmd_name'int cmd_'$name'_\1(int argc, const char **argv);|' .tmp-$$)
int cmd_$name(int argc, const char **argv);

$(sed $sed_cmd_name'extern const char *cmd_'$name'_\1_help;|' .tmp-$$)

#define CMD_${class}_CMDS(v) \\
	PA_OPT_GROUP("$(head -n1 README) - $pretty commands:"), \\
$(sed -e '$!'$sed_cmd_name"$opt_cmd_name"', \\|' \
      -e '$'$sed_cmd_name"$opt_cmd_name"'|' .tmp-$$)

#endif /* CMD_${class}_D_H */
EOF
