# SPDX-License-Identifier: GPL-3.0-or-later

build/daemon/%/entry: $(lib-obj-y) \
		      build/libusb/libusb-1.0.a \
		      libusb/libusb-1.0.pc
	mkdir -p $(@D)
	$(CC) $(LDFLAGS) -fuse-ld=$(LD) $(filter %.o,$^) \
	      $(filter %.a,$^) \
	      $(filter-out $(shell pkg-config --libs $(filter %.pc,$^)),\
			   $(shell pkg-config --static --libs \
					      $(filter %.pc,$^))) \
	      -o $@

build/libusb/libusb-1.0.a: libusb/libusb-1.0.a
	mkdir -p $(@D)
	ln -f $< $@

libusb/libusb-1.0.a libusb/libusb-1.0.pc:
	$(error No $@ found. \
		Run 'scripts/build-$(firstword $(subst /, ,$@)).sh' first)

build/daemon/cmdtree:

build/daemon/.commands:
